name: Sync with S3

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli

      - name: Sync with S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAZ2C5545XHY2WVCGB }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.mbov2kE10ycgB1ZojrAHQSVg8ZanfTNK2CAJpgQ9 }}
          AWS_DEFAULT_REGION: eu-north-1  
        run: |
          aws s3 sync . s3://rtaib-cicd952/